name: Bug Report
description: "소프트웨어 사용 중 발생한 버그를 보고합니다."
title: "[bug]: "
assignees:
  - swszz
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        [Github-Issues-Bug Report] 항목은 소프트웨어 사용 중 발생한 버그를 보고하는 용도입니다.  
        소프트웨어에 대한 일반적인 질문을 위한 항목은 Question 또는 E-mail (swsz@kakao.com)을 통해 연락바랍니다.         
        아래 나열된 항목에 대해 명확하게 작성하지 않을 경우 이슈가 해결되지 않은 상태로 닫힐 수 있습니다.
  - type: input
    id: release
    attributes:
      label: Release version
      description: 버그가 확인된 소프트웨어의 릴리즈 버전을 기입해 주세요.
    validations:
      required: false
  - type: input
    id: bug-detail
    attributes:
      label: bug-detail
      description: 버그 또는 증상에 대해 자세히 기입해 주세요.
    validations:
      required: true