name: New Feature
description: "필요한, 새로운 기능을 제안합니다."
title: "[enhancement]: "
assignees:
  - swszz
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        [Github-Issues-New Feature] 항목은 소프트웨어를 사용하면서 필요하다고 생각하거나 존재하지 않는 새로운 기능에 대한 적용을 제안하는 용도입니다.  
        소프트웨어에 대한 일반적인 질문을 위한 항목은 Question 또는 E-mail (swsz@kakao.com)을 통해 연락바랍니다.
        아래 나열된 항목에 대해 명확하게 작성하지 않을 경우 이슈가 해결되지 않은 상태로 닫힐 수 있습니다.
  - type: input
    id: feature
    attributes:
      label: feature
      description: 필요하다고 생각하거나 존재하지 않는 새로운 기능에 대해 자세히 기입해 주세요.
    validations:
      required: true