name: Question
description: "소프트웨어에 대한 일반적인 질문을 합니다."
title: "[question]: "
assignees:
  - swszz
labels: [ "question" ]
body:
  - type: markdown
    attributes:
      value: |
        [Github-Issues-Question] 항목은 소프트웨어에 대한 일반적인 질문 용도입니다.           
        아래 나열된 항목에 대해 명확하게 작성하지 않을 경우 이슈가 해결되지 않은 상태로 닫힐 수 있습니다.
  - type: input
    id: question
    attributes:
      label: question
      description: 소프트웨어에 대한 궁금한 사항을 입력해 주세요.
    validations:
      required: true